name: CICD

on:
  push:
    branches: [00_Creando_CICD_Pipeline]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3  
        with:
          distribution: 'temurin' 
          java-version: '11'

      - name: Build Project
        run: |
          cd Back/api
          mvn clean install -DskipTests

      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: |
          cd Back/api
          docker build -t viajecito/api:viajecito-backend .

      - name: Publish image to DockerHub
        run: docker push viajecito/api:viajecito-backend
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps: 
      - name: Pull image from DockerHub
        run: sudo docker pull viajecito/api:viajecito-backend

      - name: Delete old containers
        run: sudo docker rm -f viajecito-backend-container

      - name: Run docker container
        run: sudo docker run -d -p 8089:8089 --name viajecito-backend-container viajecito/api:viajecito-backend

